### ISSUE TITLE
更新以后openai api的用不了

### ISSUE THREAD

**Issue by msola-ht** [MinusZoneAI/ComfyUI-Prompt-MZ#12]
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! No module named 'mz_openaiapi'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\ComfyUI-Prompt-MZ\__init__.py", line 431, in encode
    import mz_openaiapi
ModuleNotFoundError: No module named 'mz_openaiapi'

**Comment by wailovet** [comment]
更新后再试试看
